name: Fetch Repo Name
description: This action Prints Repo Name

inputs:
  TestInp:
    description: 'Input test'
    required: false
    default: ""

outputs:
  TestOutput:
    description: 'Output Test'
    value: ${{ steps.test.outputs.TestOutput }}

runs:
  using: 'composite'
  steps:
    - name: Set Env Variable
      shell: pwsh
      run: |
        echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV
    - name: Test
      id: test
      shell: pwsh
      run: |
        Write-Host "Starting..."
        Write-Host "TestInp: ${{ inputs.TestInp }}"
        Write-Host "output: ${{ github.repository }} "
        $repo = "${{ github.repository }}"
        Write-Host "Repo: $repo "
        $repoName = ($repo.Split('/'))[1]
        Write-Host "RepoName: $repoName "
        echo "TestOutput=true" >> $GITHUB_OUTPUT
        Write-Host "powershell script"
        $scriptPath = Resolve-Path "${{github.action_path}}\fetchRepoName.ps1"
        . $scriptPath
        Write-Host " *************** END *************** " 
